source "https://rubygems.org"
gem "kramdown-parser-gfm"
gem "tzinfo-data"
gem "jekyll", "~> 3.7"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "faraday-retry"
gem "webrick", "~> 1.8"
